#!/usr/bin/env bash
# make_apps.sh - build the two CapCut Eyes app bundles from the published launchers.
#
#   CapCut Eyes.app       the floating control pad   (tools/sa_eyes_pad.py)
#   CapCut Eyes Menu.app  the menu-bar indicator     (tools/sa_watchbar.py)
#
# Usage, from anywhere:
#   apps/capcut-eyes/make_apps.sh                         # bundles land in apps/capcut-eyes/build/
#   WORKSPACE=/path/to/workspace apps/capcut-eyes/make_apps.sh
#   OUT_DIR="$HOME/Applications" apps/capcut-eyes/make_apps.sh
#   apps/capcut-eyes/make_apps.sh --help
#
# Settings (environment variables, all optional):
#   WORKSPACE      folder that holds tools/ and receives Sessions/_eyes/   default: the repository root
#   TOOLS_DIR      folder with sa_eyes.py, sa_eyes_pad.py, sa_watchbar.py  default: $WORKSPACE/tools
#   PYTHON         interpreter with tkinter, rumps and pyobjc Quartz       default: $TOOLS_DIR/venv/bin/python3,
#                                                                          else python3 on PATH
#   LAUNCHERS      folder with the source launchers                        default: workspace-kit/launchers
#   OUT_DIR        where the .app bundles are written                      default: apps/capcut-eyes/build
#   BUNDLE_PREFIX  bundle identifier prefix                                default: local.capcut-eyes
#
# What it does: copies each launcher script into a minimal .app bundle, swaps the placeholder
# workspace path in the launcher for WORKSPACE / TOOLS_DIR / PYTHON (baked in at build time,
# overridable at run time), writes a minimal Info.plist and checks the result. It never touches
# CapCut, its projects or anything outside OUT_DIR.
#
# Status: Experimental. The bundles are unsigned. macOS privacy controls can stop an unsigned
# app opened from Finder reading ~/Movies (where CapCut keeps its projects) or ~/Documents. The
# route that has been verified in use is starting the menu-bar controller from a Terminal or
# agent session that already has that access:  "$PYTHON" tools/sa_watchbar.py
# See apps/capcut-eyes/README.md.
#
# Written by an AI coding agent under Saad Ahmad's direction.

set -euo pipefail

usage() {
  sed -n '2,32p' "$0" | sed 's/^# \{0,1\}//'
}

case "${1:-}" in
  -h|--help) usage; exit 0 ;;
  "") ;;
  *) echo "make_apps.sh: unknown argument '$1' (try --help)" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/../.." && pwd)"

WORKSPACE="${WORKSPACE:-$REPO_ROOT}"
if [ ! -d "$WORKSPACE" ]; then
  echo "make_apps.sh: WORKSPACE is not a folder: $WORKSPACE" >&2
  exit 1
fi
WORKSPACE="$(cd "$WORKSPACE" && pwd)"

if [ -z "${TOOLS_DIR:-}" ]; then
  if [ -f "$WORKSPACE/tools/sa_eyes.py" ]; then
    TOOLS_DIR="$WORKSPACE/tools"
  else
    TOOLS_DIR="$WORKSPACE/Tools"
  fi
fi

if [ -z "${PYTHON:-}" ]; then
  if [ -x "$TOOLS_DIR/venv/bin/python3" ]; then
    PYTHON="$TOOLS_DIR/venv/bin/python3"
  else
    PYTHON="$(command -v python3 || true)"
  fi
fi
if [ -z "$PYTHON" ] || [ ! -x "$PYTHON" ]; then
  echo "make_apps.sh: no usable python3 found; set PYTHON=/path/to/python3" >&2
  exit 1
fi

LAUNCHERS="${LAUNCHERS:-$REPO_ROOT/workspace-kit/launchers}"
OUT_DIR="${OUT_DIR:-$HERE/build}"
BUNDLE_PREFIX="${BUNDLE_PREFIX:-local.capcut-eyes}"
MARKER="built-by-make_apps.txt"

for tool in sa_eyes.py sa_eyes_pad.py sa_watchbar.py sa_editwatch.py sa_screenwatch.py; do
  if [ ! -f "$TOOLS_DIR/$tool" ]; then
    echo "make_apps.sh: $TOOLS_DIR/$tool is missing; set TOOLS_DIR to the folder that holds the CapCut Eyes tools" >&2
    exit 1
  fi
done

# Wrap a value in single quotes for a zsh script: ' becomes '\''
sh_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# Literal (not regex) find-and-replace on stdin, safe for paths with spaces or symbols.
replace_literal() {
  FIND="$1" REPL="$2" perl -pe 's/\Q$ENV{FIND}\E/$ENV{REPL}/g'
}

# Turn a published launcher into a bundle executable that reads WORKSPACE / TOOLS_DIR / PYTHON.
render_launcher() {
  local src="$1"
  local old_root
  # The first `cd "<path>"` line, with or without a trailing `|| exit 1`.
  old_root="$(sed -n 's/^cd "\([^"]*\)".*$/\1/p' "$src" | head -n 1)"
  if [ -z "$old_root" ]; then
    echo "make_apps.sh: cannot find the workspace path (a cd \"...\" line) in $src" >&2
    return 1
  fi
  local shebang
  shebang="$(head -n 1 "$src")"
  case "$shebang" in
    '#!'*) ;;
    *) echo "make_apps.sh: $src has no #! line" >&2; return 1 ;;
  esac
  printf '%s\n' "$shebang"
  printf '# Generated by apps/capcut-eyes/make_apps.sh from %s.\n' "$(basename "$src")"
  printf '# Run-time overrides: WORKSPACE, TOOLS_DIR, PYTHON.\n'
  printf 'if [ -z "${WORKSPACE:-}" ]; then WORKSPACE=%s; fi\n' "$(sh_quote "$WORKSPACE")"
  printf 'if [ -z "${TOOLS_DIR:-}" ]; then TOOLS_DIR=%s; fi\n' "$(sh_quote "$TOOLS_DIR")"
  printf 'if [ -z "${PYTHON:-}" ]; then PYTHON=%s; fi\n' "$(sh_quote "$PYTHON")"
  tail -n +2 "$src" \
    | replace_literal "$old_root/Tools/venv/bin/python3" '${PYTHON}' \
    | replace_literal "$old_root/Tools/" '${TOOLS_DIR}/' \
    | replace_literal "$old_root" '${WORKSPACE}'
}

write_plist() {
  local plist="$1" executable="$2" identifier="$3" name="$4"
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleDisplayName</key>
  <string>${name}</string>
  <key>CFBundleExecutable</key>
  <string>${executable}</string>
  <key>CFBundleIdentifier</key>
  <string>${identifier}</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>${name}</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>2.0</string>
  <key>CFBundleVersion</key>
  <string>2</string>
  <key>LSMinimumSystemVersion</key>
  <string>12.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSHighResolutionCapable</key>
  <true/>
</dict>
</plist>
PLIST
}

build_app() {
  local app_name="$1" launcher="$2" executable="$3" identifier="$4"
  local src="$LAUNCHERS/$launcher"
  local app="$OUT_DIR/$app_name.app"

  if [ ! -f "$src" ]; then
    echo "make_apps.sh: launcher not found: $src" >&2
    return 1
  fi
  if [ -e "$app" ]; then
    if [ -f "$app/Contents/Resources/$MARKER" ]; then
      rm -rf "$app"
    else
      echo "make_apps.sh: $app exists and was not built by this script; refusing to replace it" >&2
      return 1
    fi
  fi

  mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
  # Marker first, so a failed build can always be replaced by the next run.
  printf 'Built from %s by apps/capcut-eyes/make_apps.sh\n' "$launcher" \
    > "$app/Contents/Resources/$MARKER"
  if ! render_launcher "$src" > "$app/Contents/MacOS/$executable"; then
    rm -rf "$app"
    return 1
  fi
  chmod 755 "$app/Contents/MacOS/$executable"
  write_plist "$app/Contents/Info.plist" "$executable" "$identifier" "$app_name"

  if command -v plutil >/dev/null 2>&1; then
    plutil -lint -s "$app/Contents/Info.plist"
  fi
  if command -v zsh >/dev/null 2>&1; then
    zsh -n "$app/Contents/MacOS/$executable"
  fi
  if grep -q '/Users/you/' "$app/Contents/MacOS/$executable"; then
    echo "make_apps.sh: a placeholder path survived in $app; check the launcher" >&2
    return 1
  fi
  echo "built  $app"
}

mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

build_app "CapCut Eyes" "capcut_eyes.command" "CapCutEyes" "$BUNDLE_PREFIX"
build_app "CapCut Eyes Menu" "capcut_eyes_menu.zsh" "CapCutEyesMenu" "$BUNDLE_PREFIX.menu"

cat <<NEXT

WORKSPACE  $WORKSPACE
TOOLS_DIR  $TOOLS_DIR
PYTHON     $PYTHON

Next:
  1. The pad needs tkinter; the menu bar needs rumps; the screen watcher needs pyobjc's Quartz:
       "$PYTHON" -m pip install rumps pyobjc-framework-Quartz
  2. Self-checks:  "$PYTHON" "$TOOLS_DIR/sa_eyes.py" test
                   "$PYTHON" "$TOOLS_DIR/sa_watchbar.py" --test
  3. macOS will ask for Screen Recording permission the first time CapCut's window is captured.
  4. If an app opened from Finder cannot read ~/Movies or ~/Documents, start the menu bar from a
     Terminal that can:  "$PYTHON" "$TOOLS_DIR/sa_watchbar.py"
NEXT
