#!/usr/bin/env python3
"""sa_toolindex — the tool catalogue, generated from the tools themselves.

The workspace holds many small scripts and the house rule is CHECK BEFORE NEW — but a
hand-maintained map goes stale, and a fresh session either rescans everything or rebuilds
what already exists (sa_clickdetect was nearly rebuilt from scratch on 9 Aug because
nothing surfaced it). This generates one line per tool from each script's own docstring,
so the index cannot drift from reality.

    Tools/venv/bin/python3 Tools/sa_toolindex.py          # writes Reference/TOOLS_CATALOG.md
    Tools/venv/bin/python3 Tools/sa_toolindex.py --test

Also flags hygiene: tools with no docstring, and tools with no --test. From the 9 Aug
harness sweep (Reference/HARNESS_IDEAS.md, "Do now" #5).
"""
import ast
import datetime
import pathlib
import sys

TOOLS = pathlib.Path(__file__).resolve().parent
OUT = TOOLS.parent / "Reference" / "TOOLS_CATALOG.md"


def first_line(doc):
    """The one-line summary: first non-empty docstring line, tool name prefix stripped."""
    if not doc:
        return None
    for line in doc.strip().splitlines():
        line = line.strip()
        if line:
            # docstrings here open "sa_foo — does the thing"; keep just the doing part
            for sep in (" — ", " -- ", " - "):
                if sep in line and line.split(sep)[0].strip().startswith("sa_"):
                    return line.split(sep, 1)[1].strip()
            return line
    return None


def describe(path):
    """-> (summary, has_test) parsed from the AST — never imports the tool."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except SyntaxError:
        return "(does not parse)", False
    doc = ast.get_docstring(tree)
    src = path.read_text(encoding="utf-8")
    return first_line(doc), ("--test" in src or "def _test" in src or "--self-test" in src)


def build():
    rows, bare, untested = [], [], []
    for p in sorted(TOOLS.glob("sa_*.py")):
        if p.name.endswith(".bak"):
            continue
        summary, tested = describe(p)
        if not summary:
            bare.append(p.name)
            summary = "(no docstring)"
        if not tested:
            untested.append(p.name)
        rows.append((p.name, summary, tested))
    return rows, bare, untested


def render(rows, bare, untested):
    stamp = datetime.date.today().strftime("%d %b %Y")
    L = ["> hub: [[INDEX]] · [[CLAUDE]] — GENERATED by Tools/sa_toolindex.py, do not edit",
         "",
         f"# Tool catalogue — {len(rows)} tools, generated {stamp}",
         "",
         "One line per tool, read from each script's own docstring. **Check here before",
         "building anything new** — much is already solved.",
         "",
         "| Tool | What it does | --test |",
         "|---|---|---|"]
    for name, summary, tested in rows:
        L.append(f"| `{name}` | {summary} | {'yes' if tested else '—'} |")
    if bare or untested:
        L += ["", "## Hygiene",
              f"- no docstring: {', '.join(bare) if bare else 'none'}",
              f"- no self-test: {', '.join(untested) if untested else 'none'}"]
    return "\n".join(L) + "\n"


def _test():
    assert first_line("sa_foo — paces a video to the voice.\nMore.") == \
        "paces a video to the voice."
    assert first_line("Safe launcher for X.") == "Safe launcher for X."
    assert first_line("") is None and first_line(None) is None
    rows, bare, untested = build()
    assert len(rows) > 40, f"expected the full toolbox, found {len(rows)}"
    me = [r for r in rows if r[0] == "sa_toolindex.py"]
    assert me and me[0][2], "this tool must find itself, with its own test"
    md = render(rows, bare, untested)
    assert md.count("| `sa_") == len(rows), "every tool gets exactly one row"
    assert "GENERATED" in md.splitlines()[0], "the file must declare it is generated"
    print(f"sa_toolindex self-check: ok ({len(rows)} tools, {len(bare)} bare, "
          f"{len(untested)} untested)")


if __name__ == "__main__":
    if "--test" in sys.argv:
        _test()
        sys.exit()
    rows, bare, untested = build()
    OUT.write_text(render(rows, bare, untested), encoding="utf-8")
    print(f"-> {OUT}  ({len(rows)} tools; {len(bare)} without docstrings, "
          f"{len(untested)} without --test)")
